#!/usr/bin/env bash

# Set version to Windows 10.
"$WINELOADER" winecfg /v win10

# Use local installer in user Downloads folder if present.
dl_dir=$(xdg-user-dir DOWNLOAD)
if [[ -e "${dl_dir}/${INSTALLER_NAME}" ]]; then
    # Unset INSTALL_URL from snapcraft.yaml.
    export INSTALL_URL=
    # Set INSTALL_EXE.
    export INSTALL_EXE="${dl_dir}/${INSTALLER_NAME}"
fi
