name: map-creator-unofficial
base: core20
# adopt-info: installer
version: '2.3.2'
grade: stable
summary: Create language-specific maps, charts, diagrams, and timelines.
description: |
  Map Creator simplifies the creation of language-specific maps, charts, diagrams, and timelines for Bible lessons and world geography.

confinement: strict
architectures:
  - amd64

license: GPL-3.0+
contact: https://github.com/wasta-linux/map-creator-snap

environment:
  TRICKS: "corefonts vcrun2013"
  WINEDLLOVERRIDES: "mscoree,mshtml=" # Prevent pop-ups about Wine Mono and Wine Gecko

# layout:
#   /etc/wgetrc:
#     symlink: $SNAP/etc/wgetrc

apps:
  map-creator:
    extensions: [gnome-3-38]
    environment:
      INSTALL_URL: "https://s3.amazonaws.com/fmosoft/MapCreatorSetup-x64-2.3.2.exe"
      INSTALL_FLAGS: "/quiet"
      RUN_EXE: "C:/Program Files/FMOsoft/MapCreator/MapCreator.exe"
    command: bin/sommelier run-exe

  init:
    extensions: [gnome-3-38]
    command: bin/sommelier
    environment:
      INIT: '1'

  wine:
    extensions: [gnome-3-38]
    command: bin/sommelier

  winecfg:
    extensions: [gnome-3-38]
    command: bin/sommelier winecfg

  winetricks:
    extensions: [gnome-3-38]
    command: bin/sommelier winetricks

plugs:
  # audio-playback:
  desktop:
  desktop-legacy:
  home:
  network:
  # network-bind:
  removable-media:
  x11:
  wayland:

  wine-runtime:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime
  wine-7-stable:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-7-stable-core20

parts:
  hooks:
    plugin: dump
    source: hooks/
    organize:
      "*": sommelier/hooks/
    stage:
      - sommelier

  sommelier-core:
    plugin: make
    source: https://github.com/snapcrafters/sommelier-core.git
    # Need "master" for core 20 b/c of https://github.com/mmtrt/sommelier-core/commit/096bb179b975df5a89e88b3bac048901ded465fc
    # The part fails to build otherwise.
    source-branch: "master"
    override-prime: |
      snapcraftctl prime

      # Force use of wine64 executable.
      sed -r -i 's|(\$WINE_PLATFORM/bin/wine)|\164|' bin/sommelier

      # Don't let yad dialogs stay always-on-top.
      sed -r -i 's|(yad.*) --on-top|\1|g' bin/sommelier
      # Remove annoying yad dialog for interactive MSI install.
      sed -r -i 's|(yes.*Installing .*EXE_NAME.*)|# \1|' bin/sommelier
      sed -r -i 's|(.*INSTALL_YAD_PID)|# \1|g' bin/sommelier

      # Add init-only command.
      sed -r -i 's|(\s+)(init_wine)$|\1\2\n\1if [[ $INIT == '1' ]]; then exit 0; fi|' bin/sommelier
