name: map-creator-unofficial
title: Map Creator (via WINE)
base: core20
version: '2.3.2' # matches installer version below
grade: stable
summary: Create language-specific maps, charts, diagrams, and timelines.
description: |
  Map Creator simplifies the creation of language-specific maps, charts, diagrams, and timelines for Bible lessons and world geography.
confinement: strict
license: Proprietary
website: https://github.com/wasta-linux/map-creator-snap
contact: nate_marti@sil.org
issues: https://github.com/wasta-linux/map-creator-snap/issues
icon: snap/gui/map-creator-unofficial.png
architectures:
  - amd64

environment:
  INSTALLER_NAME: "MapCreatorSetup-x64-2.3.2.exe"
  SOMMELIER_NO_THEME: "true" # avoid theme errors
  SYSTEM_WGETRC: $SNAP/wine-runtime/etc/wgetrc
  TRICKS: "corefonts vcrun2013"
  WINEDLLOVERRIDES: "$WINEDLLOVERRIDES;mscoree=;mshtml=" # Prevent pop-ups about Wine Mono and Wine Gecko

apps:
  map-creator:
    extensions: [gnome-3-38]
    command: bin/sommelier run-exe
    environment:
      # MapCreator downloads: http://fmosoft.com/download
      INSTALL_URL: "https://s3.amazonaws.com/fmosoft/${INSTALLER_NAME}"
      INSTALL_FLAGS: "/quiet"
      RUN_EXE: "C:/Program Files/FMOsoft/MapCreator/MapCreator.exe"

  init:
    extensions: [gnome-3-38]
    command: bin/sommelier
    environment:
      INIT: '1'

  remove-wine-prefix:
    extensions: [gnome-3-38]
    command: bin/sommelier winetricks annihilate

  wine:
    extensions: [gnome-3-38]
    command: bin/sommelier $WINEPREFIX

  winecfg:
    extensions: [gnome-3-38]
    command: bin/sommelier winecfg

  winetricks:
    extensions: [gnome-3-38]
    command: bin/sommelier winetricks

plugs:
  desktop:
  desktop-legacy:
  home:
  network:
  removable-media:
  wayland:
  x11:

  wine-runtime-c20:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime-core20
  wine-7-stable:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-7-stable-core20

parts:
  # This reverts changes from https://github.com/snapcore/snapcraft/pull/3586
  fix-fontconfig:
    plugin: nil
    after: [gnome-3-38-extension]
    override-prime: |
      sed -i '/snap-package/,+1d' $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch

  # Ref: https://github.com/mmtrt/notepad-plus-plus
  fix-bindtext:
    plugin: nil
    after: [gnome-3-38-extension]
    override-prime: |
      sed -i "$(grep -in bindtext $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch | cut -d':' -f1 | tail -2 | head -1)d" $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch
      sed -i "$(grep -in bindtext $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch | cut -d':' -f1 | tail -1)d" $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch

  hooks:
    plugin: dump
    source: hooks/
    organize:
      "*": sommelier/hooks/
    stage:
      - sommelier

  sommelier-core:
    plugin: make
    source: https://github.com/snapcrafters/sommelier-core.git
    source-branch: "1.0"
    override-prime: |
      snapcraftctl prime

      # Don't let yad dialogs stay always-on-top.
      sed -r -i 's|(yad.*) --on-top|\1|g' bin/sommelier
      # # Remove annoying yad dialog for interactive MSI install.
      # sed -r -i 's|(yes.*Installing .*EXE_NAME.*)|# \1|' bin/sommelier
      # sed -r -i 's|(.*INSTALL_YAD_PID)|# \1|g' bin/sommelier

      # Add init-only command.
      sed -r -i 's|(\s+)(init_wine)$|\1\2\n\1if [[ $INIT == '1' ]]; then exit 0; fi|' bin/sommelier
