name: map-creator-unofficial
base: core18
# base: core20
# adopt-info: installer
version: '2.3.2'
grade: stable
summary: Create language-specific maps, charts, diagrams, and timelines.
description: |
  Map Creator simplifies the creation of language-specific maps, charts, diagrams, and timelines for Bible lessons and world geography.

confinement: strict # use 'strict' once you have the right plugs and slots
architectures:
  - amd64

license: GPL-3.0+
contact: https://github.com/wasta-linux/map-creator-snap

environment:
  TRICKS: "corefonts vcrun2013"
  WINEDLLOVERRIDES: "mscoree,mshtml=" # Prevent pop-ups about Wine Mono and Wine Gecko
  XDG_CACHE_HOME: $SNAP_REAL_HOME/.cache # won't work with full confinement b/c of hidden dir

apps:
  map-creator:
    # extensions: [gnome-3-38] # core20
    extensions: [gnome-3-28] # core18
    environment:
      INSTALL_URL: "https://s3.amazonaws.com/fmosoft/MapCreatorSetup-x64-2.3.2.exe"
      # INSTALL_EXE: "${SNAP}/installer/setup.exe"
      INSTALL_FLAGS: "/quiet"
      RUN_EXE: "C:/Program Files/FMOsoft/MapCreator/MapCreator.exe"
    command: bin/sommelier run-exe
    #desktop: gui/cardsorter.desktop

  init:
    # extensions: [gnome-3-38] # core20
    extensions: [gnome-3-28] # core18
    command: bin/sommelier
    environment:
      INIT: '1'

  wine:
    # extensions: [gnome-3-38] # core20
    extensions: [gnome-3-28] # core18
    command: bin/sommelier
    # plugs:
    #   - home
    #   - network
    #   - process-control
    #   - system-observe
    #   - system-trace

  winecfg:
    # extensions: [gnome-3-38] # core20
    extensions: [gnome-3-28] # core18
    command: bin/sommelier winecfg

  winetricks:
    # extensions: [gnome-3-38] # core20
    extensions: [gnome-3-28] # core18
    command: bin/sommelier winetricks
    # plugs:
    #   - network # for downloading

plugs:
  # audio-playback:
  desktop:
  desktop-legacy:
  home:
  # network:
  # network-bind:
  removable-media:
  x11:
  wayland:

  wine-runtime:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime
  # wine-7-stable: # number must match the number in default-provider
  # wine-6-staging: # number must match the number in default-provider
  wine-6-stable: # number must match the number in default-provider
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-6-stable # must be a valid snap
    # default-provider: wine-platform-6-staging # must be a valid snap
    # default-provider: wine-platform-7-stable-core20 # must be a valid snap

parts:
  # installer:
  #   plugin: dump
  #   source: installer/
  #   build-packages:
  #     - unzip
  #   override-build: |
  #     installer_zipname=$(find $SNAPCRAFT_PART_BUILD -maxdepth 1 -name 'CardSorterWPF*.zip' -exec basename {} \;)
  #     version=$(echo "$installer_zipname" | grep -Eo '[0-9]{8}')
  #     snapcraftctl set-version "$version"
  #     snapcraftctl set-grade "devel"
  #     unzip ${SNAPCRAFT_PART_BUILD}/CardSorterWPF*.zip -d ${SNAPCRAFT_PART_INSTALL}/installer
  #     # snapcraftctl build
  #   stage:
  #     - installer/

  hooks:
    plugin: dump
    source: hooks/
    organize:
      "*": sommelier/hooks/
    stage:
      - sommelier

  sommelier-core:
    plugin: make
    source: https://github.com/snapcrafters/sommelier-core.git
    source-branch: "1.0" # core18
    # need "master" for core20 b/c of https://github.com/mmtrt/sommelier-core/commit/096bb179b975df5a89e88b3bac048901ded465fc
    # source-branch: "master"
    override-prime: |
      snapcraftctl prime

      # Don't let yad dialogs stay always-on-top.
      sed -r -i 's|(yad.*) --on-top|\1|g' bin/sommelier
      # Remove annoying yad dialog for interactive MSI install.
      sed -r -i 's|(yes.*Installing .*EXE_NAME.*)|# \1|' bin/sommelier
      sed -r -i 's|(.*INSTALL_YAD_PID)|# \1|g' bin/sommelier

      # Add init-only command.
      sed -r -i 's|(\s+)(init_wine)$|\1\2\n\1if [[ $INIT == '1' ]]; then exit 0; fi|' bin/sommelier

      # Copy cached winetricks in $SNAP_REAL_HOME before installing winetricks.
      sed -r -i 's@(^install_app\(\).*)@\1\n  cp -r "${SNAP_REAL_HOME}/.cache/winetricks" "${SNAP_USER_COMMON}/.cache" || true@' bin/sommelier
